/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class c32_memory_SMMalloc_CacheWarmupOptions */

#ifndef _Included_c32_memory_SMMalloc_CacheWarmupOptions
#define _Included_c32_memory_SMMalloc_CacheWarmupOptions
#ifdef __cplusplus
extern "C" {
#endif
#undef c32_memory_SMMalloc_CacheWarmupOptions_CACHE_COLD
#define c32_memory_SMMalloc_CacheWarmupOptions_CACHE_COLD 0L
#undef c32_memory_SMMalloc_CacheWarmupOptions_CACHE_WARM
#define c32_memory_SMMalloc_CacheWarmupOptions_CACHE_WARM 1L
#undef c32_memory_SMMalloc_CacheWarmupOptions_CACHE_HOT
#define c32_memory_SMMalloc_CacheWarmupOptions_CACHE_HOT 2L
#ifdef __cplusplus
}
#endif
#endif
