/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class c32_extern_SMMalloc */

#ifndef _Included_c32_extern_SMMalloc
#define _Included_c32_extern_SMMalloc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     c32_extern_SMMalloc
 * Method:    _sm_allocator_create
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_c32_extern_SMMalloc__1sm_1allocator_1create
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     c32_extern_SMMalloc
 * Method:    _sm_allocator_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_c32_extern_SMMalloc__1sm_1allocator_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     c32_extern_SMMalloc
 * Method:    _sm_allocator_thread_cache_create
 * Signature: (JI[I)V
 */
JNIEXPORT void JNICALL Java_c32_extern_SMMalloc__1sm_1allocator_1thread_1cache_1create__JI_3I
  (JNIEnv *, jclass, jlong, jint, jintArray);

/*
 * Class:     c32_extern_SMMalloc
 * Method:    _sm_allocator_thread_cache_create
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_c32_extern_SMMalloc__1sm_1allocator_1thread_1cache_1create__JII
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     c32_extern_SMMalloc
 * Method:    _sm_allocator_thread_cache_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_c32_extern_SMMalloc__1sm_1allocator_1thread_1cache_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     c32_extern_SMMalloc
 * Method:    _sm_malloc
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_c32_extern_SMMalloc__1sm_1malloc
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     c32_extern_SMMalloc
 * Method:    _sm_free
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_c32_extern_SMMalloc__1sm_1free
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     c32_extern_SMMalloc
 * Method:    _sm_realloc
 * Signature: (JJJJ)J
 */
JNIEXPORT jlong JNICALL Java_c32_extern_SMMalloc__1sm_1realloc
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     c32_extern_SMMalloc
 * Method:    _sm_msize
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_c32_extern_SMMalloc__1sm_1msize
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     c32_extern_SMMalloc
 * Method:    _sm_mbucket
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_c32_extern_SMMalloc__1sm_1mbucket
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     c32_extern_SMMalloc
 * Method:    _sm_buckets_count
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_c32_extern_SMMalloc__1sm_1buckets_1count
  (JNIEnv *, jclass, jlong);

/*
 * Class:     c32_extern_SMMalloc
 * Method:    _sm_buckets_element_count
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_c32_extern_SMMalloc__1sm_1buckets_1element_1count
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     c32_extern_SMMalloc
 * Method:    _sm_is_my_alloc
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_c32_extern_SMMalloc__1sm_1is_1my_1alloc
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
